
CREATE TABLE
    OBS_UNIT_SET_STATUS
    (
        STATUS_ENTITY_ID              VARCHAR(64) not null,
        DOMAIN_ENTITY_STATE           VARCHAR(64) not null,
        OBS_PROJECT_ID                VARCHAR(64) not null,
        FLAGS                         VARCHAR(200),
        PRIMARY KEY(STATUS_ENTITY_ID)
    );

CREATE TABLE
    AQUA_OUS_FLAG
(
    OUS_STATUS_ENTITY_ID              VARCHAR(64) not null,
    FLAG_NAME                VARCHAR(64) not null,
    FLAG_VALUE           VARCHAR(64) not null,
    PRIMARY KEY(OUS_STATUS_ENTITY_ID)
);



-- INSERT INTO OBS_UNIT_SET_STATUS (STATUS_ENTITY_ID, DOMAIN_ENTITY_STATE, FLAGS) VALUES ('uid://A001/X21f/X19', 'ReadyForProcessing', 'PipelineCalibration');
-- INSERT INTO OBS_UNIT_SET_STATUS (STATUS_ENTITY_ID, DOMAIN_ENTITY_STATE, FLAGS) VALUES ('uid://A001/X2fb/Xe4e', 'ReadyForProcessing', 'PipelineCalibration');
-- INSERT INTO OBS_UNIT_SET_STATUS (STATUS_ENTITY_ID, DOMAIN_ENTITY_STATE, FLAGS) VALUES ('uid://A001/X2fb/Xe54', 'ReadyForProcessing', 'PipelineCalibration');
-- INSERT INTO OBS_UNIT_SET_STATUS (STATUS_ENTITY_ID, DOMAIN_ENTITY_STATE, FLAGS) VALUES ('uid://A001/X2fb/Xe5a', 'ReadyForProcessing', 'PipelineCalibration');
-- INSERT INTO OBS_UNIT_SET_STATUS (STATUS_ENTITY_ID, DOMAIN_ENTITY_STATE, FLAGS) VALUES ('uid://A001/X2fb/X386', 'ReadyForProcessing', 'PipelineCalibration');
--
-- INSERT INTO AQUA_OUS_FLAG (OUS_STATUS_ENTITY_ID, FLAG_NAME, FLAG_VALUE) VALUES ('uid://A001/X21f/X19', 'PL_PROCESSING_EXECUTIVE', 'EU');
-- INSERT INTO AQUA_OUS_FLAG (OUS_STATUS_ENTITY_ID, FLAG_NAME, FLAG_VALUE) VALUES ('uid://A001/X2fb/Xe4e', 'PL_PROCESSING_EXECUTIVE', 'EU');
-- INSERT INTO AQUA_OUS_FLAG (OUS_STATUS_ENTITY_ID, FLAG_NAME, FLAG_VALUE) VALUES ('uid://A001/X2fb/Xe54', 'PL_PROCESSING_EXECUTIVE', 'EU');
-- INSERT INTO AQUA_OUS_FLAG (OUS_STATUS_ENTITY_ID, FLAG_NAME, FLAG_VALUE) VALUES ('uid://A001/X2fb/Xe5a', 'PL_PROCESSING_EXECUTIVE', 'EU');
-- INSERT INTO AQUA_OUS_FLAG (OUS_STATUS_ENTITY_ID, FLAG_NAME, FLAG_VALUE) VALUES ('uid://A001/X2fb/X386', 'PL_PROCESSING_EXECUTIVE', 'EU');
